wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692426497.449617
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 95
      3:
      - 17
      - 23
      - 37
      4: 3.10.12
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
